plugins {
    id 'com.gradleup.shadow'
    id "me.shedaniel.unified-publishing" version "0.1.+"
}

loom {
    accessWidenerPath = project(":common").loom.accessWidenerPath
    injectAccessWidener(tasks.named('shadowJar'))
}

architectury {
    platformSetupLoomIde()
    fabric()
}

configurations {
    common
    shadowCommon
    compileClasspath.extendsFrom common
    runtimeClasspath.extendsFrom common
    developmentFabric.extendsFrom common
}

dependencies {
    implementation libs.fabric.loader

    // Fabric API. This is technically optional, but you probably want it anyway.
    implementation libs.fabric.api

    implementation(libs.cloth.config.fabric) {
        exclude(group: "net.fabricmc.fabric-api")
    }

    compileOnly libs.modmenu

    common(project(path: ':common')) { transitive false }
    shadowCommon(project(path: ':common', configuration: 'transformProductionFabric')) { transitive false }
}

processResources {
    inputs.property 'version', project.version

    filesMatching('fabric.mod.json') {
        expand version: project.version
    }
}

def mcVersion = libs.versions.minecraft.get()

jar {
    archiveClassifier = 'raw'
}

shadowJar {
    dependsOn jar
    configurations = [project.configurations.shadowCommon]
    archiveClassifier = null
    archiveVersion = "$project.version+$mcVersion"
}

assemble.dependsOn shadowJar

unifiedPublishing {
    project {
        displayName = "[Fabric $mcVersion] v$rootProject.mod_version"
        releaseType = "beta"
        gameVersions = ["26.1.x"]
        gameLoaders = ["fabric"]

        mainPublication jar

        relations {
            depends {
                curseforge = "cloth-config"
                modrinth = "cloth-config"
            }
            depends {
                curseforge = "fabric-api"
                modrinth = "fabric-api"
            }
            optional {
                curseforge = "modmenu"
                modrinth = "modmenu"
            }
        }

        if (rootProject.hasProperty("curse_api_key") || System.getenv("CURSE_API_KEY") != null) {
            curseforge {
                token = rootProject.hasProperty("curse_api_key") ? rootProject.property("curse_api_key") : System.getenv("CURSE_API_KEY")
                id = rootProject.curseforge_id
                gameVersions.addAll "Java 25"
            }
        }

        if (rootProject.hasProperty("modrinth_key") || System.getenv("MODRINTH_TOKEN") != null) {
            modrinth {
                token = rootProject.hasProperty("modrinth_key") ? rootProject.property("modrinth_key") : System.getenv("MODRINTH_TOKEN")
                id = rootProject.modrinth_id
                version = "$rootProject.mod_version+$mcVersion-$project.name"
            }
        }
    }
}
